### ISSUE TITLE
📑 Feature Request: Adding infinite scroll to the issues of a repository (see image)

### ISSUE THREAD

**Issue by tarunkumar2005** [rahulsainlll/git-trace#100]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

So what i want is i want that there will be a infinite scroll feature in the place where all the issues are shown means if the issues are so many then it will not be optimal to load all the issues at a single time.

### Describe your solution to problem

Insted what we should do is that we need to create a infinite scroll in which as the user moves down just before going to the end more issues will load just like in the instagram or other infinite post apps in which list is so long or infinite and it is usefull here because issues of a repo can be so many if it is a large repo and many people are contributing to it.

### Additional context

@rahulsainlll Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add Relevant Screenshot (if available)

![image](https://github.com/user-attachments/assets/c385d40d-6bfc-4f06-af0d-f841ef8c0f04)

**Comment by NawinKumarSharma** [comment]
@tarunkumar2005, can you assign me?
