### ISSUE TITLE
📑 Feature Request: Add chatbot

### ISSUE THREAD

**Issue by NK-Works** [rahulsainlll/git-trace#101]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

I want to add a AI chatbot for the website

**Comment by Aarzookhunger** [comment]
@rahulsainlll kindly look if you want this feature to be added and also assign the level label accordingly.!

**Comment by NK-Works** [comment]
@rahulsainlll Any updates? Do i work on it or not?

**Comment by Aarzookhunger** [comment]
@NK-Works Go ahead
