### ISSUE TITLE
📑 Feature Request:  User Activity Feed

### ISSUE THREAD

**Issue by amitb0ra** [rahulsainlll/git-trace#106]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

User Activity Feed on the profile page, where users can view their recent activities. This feed will show:

Commits made by the user.
Pull requests opened.
Issues opened or closed.
Repositories starred by the user.

### Describe your solution to problem

Fetch user activity data from the GitHub API.
Display commits, pull requests, issues, and starred repositories.
Ensure that activities are sorted chronologically.
Add pagination to load more activities as the user scrolls.
Apply clean UI and proper formatting to distinguish different activity types.

### Additional context

Labels:
GSSoC-ext
Hacktoberfest

**Comment by Aarzookhunger** [comment]
Keep UI similar to website design.

**Comment by amitb0ra** [comment]
> Keep UI similar to website design.

can you add level too for gssoc-ext?

**Comment by Aarzookhunger** [comment]
> > Keep UI similar to website design.
> 
> can you add level too for gssoc-ext?

i'll add it once you create a pr for the same. I need to review the changes and then will label accordingly
