### ISSUE TITLE
📑 Feature Request: Search and Filter Features

### ISSUE THREAD

**Issue by sezallagwal** [rahulsainlll/git-trace#107]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

enhance the repository search functionality by adding advanced filtering options. This will allow users to efficiently search for repositories based on specific criteria, improving their overall experience.

### Describe your solution to problem

Proposed Filters:
Languages: Users should be able to filter repositories by programming languages (e.g., JavaScript, Python, Ruby, etc.).
Tags: Implement tag-based filtering, enabling users to narrow down results based on relevant tags or topics.
Stars: Allow users to filter repositories based on the number of stars

### Describe alternatives you have considered

Update the search interface to include filtering options.
 Integrate language, tag, and star count filters.
 Ensure filters work in conjunction with the main search function.
 Implement a clear UI to display applied filters and allow users to remove them.
 Test the filtering functionality for accuracy and performance.

### Additional context

Labels:
GSSoC-ext
Hacktoberfest

**Comment by sezallagwal** [comment]
@Aarzookhunger hey I have my exams going on till 23 So I might be a bit slow, I hope you are okay with it

**Comment by Aarzookhunger** [comment]
> @Aarzookhunger hey I have my exams going on till 23 So I might be a bit slow, I hope you are okay with it

ya no issues.
