### ISSUE TITLE
🐛 Bug Report:  Dark mode not properly implemented in login/signup component

### ISSUE THREAD

**Issue by Sourabh782** [rahulsainlll/git-trace#110]
### Describe the bug.

Currently the dark mode is not properly implemented in login and signup component, these component are same as in light mode

### Expected behavior.

The Component should follow a dark theme at dark mode

### Screenshot.

![Screenshot 2024-10-19 212359](https://github.com/user-attachments/assets/a8030a05-0c52-41ce-833f-43d9a4533e4b)

![Screenshot 2024-10-19 212345](https://github.com/user-attachments/assets/7cf0af88-0ad4-4383-ab55-cf80979c2767)

**Comment by codebysid** [comment]
are you working on this ? @Sourabh782

**Comment by Sourabh782** [comment]
> are you working on this ? @Sourabh782

Waiting for @rahulsainlll to check this issue
