### ISSUE TITLE
🐛 Bug Report: "Recent Search" Click Causes Error Popup

### ISSUE THREAD

**Issue by amitb0ra** [rahulsainlll/git-trace#114]
### Describe the bug.

When clicking on the "Recent Search" feature, users encounter a popup message stating "Uh, something went wrong." Despite having the URL correctly added to the "Search By Repository" link, the error persists, causing confusion and hindering usability.

### Explain bug encounter!

The bug occurs after users perform a search using the "Search By Repository" feature. Although the recent searches are displayed, clicking on them results in an error, leading to confusion and a negative user experience.

## Steps to Reproduce
1. Perform a search using the "Search By Repository" feature.
2. Click on any entry in the "Recent Search" list.
3. Observe the popup message indicating an error.

### Expected behavior.

When a user clicks on any entry in the "Recent Search" list, they should be directed to the corresponding repository page without encountering any error messages.

### Screenshot.
![image](https://github.com/user-attachments/assets/0994915e-6a27-4a43-8c08-3f7b1e9688c2)

Please assign this issue to me for Hacktoberfest and GSoC-ext

**Comment by avanshh99** [comment]
I would like to work on this issue and this would be my first contribution

**Comment by avanshh99** [comment]
hello @amitb0ra may i work on this issue?
