### ISSUE TITLE
🐛 Bug Report: Poor UI/UX in Todo Feature

### ISSUE THREAD

**Issue by amitb0ra** [rahulsainlll/git-trace#116]
### Describe the bug.

The "Todo" feature has significant UI/UX issues, making it hard for users to add and manage their tasks. Text is either invisible or hard to read, and the feature sometimes fails to accept the full content of a Todo item, causing frustration and usability issues.

### Explain bug encounter!

When users try to add items to the Todo list, the text is often invisible or very difficult to read due to poor design choices (e.g., wrong font color or insufficient contrast). Additionally, the Todo feature sometimes fails to accept the entire text of a task, cutting off or rejecting longer entries without clear feedback.

## Steps to Reproduce the Behavior
1. **Go to the Todo Feature**:
   - Navigate to the Todo feature in the application.

2. **Add a New Todo Item**:
   - Input any text into the Todo list and submit it.
   - Use a longer text string to test the input limit.

3. **Observe the UI/UX Issues**:
   - The text is either invisible or difficult to see due to improper design (font color or background contrast).
   - Sometimes, the entire Todo item isn't accepted, cutting off the input.

### Expected behavior.

- BETTER TODO
- Todo text should always be clearly visible and legible, with appropriate font color, size, and background contrast.
- The Todo feature should consistently accept and display the entire content of submitted tasks, regardless of length.

### Screenshot.

![image](https://github.com/user-attachments/assets/efb5fcf1-9bf8-4731-85ba-4f98c5c12389)

Please assign this issue to me for Hacktoberfest and GSoC-ext

**Comment by Khalid-212** [comment]
@amitb0ra can you assign me to this task

**Comment by Aarzookhunger** [comment]
@amitb0ra you've already been assigned some issues, so will you be able to handle along these many or shall i assign @Khalid-212 ?

**Comment by amitb0ra** [comment]
> dy been assigned some issues, so will you be able to handle along these many or shall i assign @Khalid-212 ?

no, i have only one issue pending for user page. in which i need github oauth for that feature
so, if you can asssign #121 to me i will close that last pending one too.
