### ISSUE TITLE
Enhancement in the Footer section

### ISSUE THREAD

**Issue by MuKulsoop** [rahulsainlll/git-trace#119]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

The footer of the platform could be built more beautifully displaying some info on copyright, platform and also the functions included in the existing footer.

### Describe your solution to problem

The footer seems like this :
![image](https://github.com/user-attachments/assets/facc1ff0-f095-42d2-bef7-53a921ec8cec)
It is neither attractive nor it is giving the social, copyright info.

### Describe alternatives you have considered

It can be enhanced to a footer containing much more info like this :
![image](https://github.com/user-attachments/assets/cee6bbb3-e41f-4c7f-bf1b-58b0a74dd651)
Along with the functions given in the existing footer

**Comment by MuKulsoop** [comment]
Can I work on this

**Comment by Petsamuel** [comment]
I would like to work on this, kindly assign this to me

**Comment by rahulsainlll** [comment]
this won't look good since our app has only hero page
