### ISSUE TITLE
📑 Feature Request: Add Google/GitHub Authentication (#50 not being handled by @tarunkumar2005)

### ISSUE THREAD

**Issue by amitb0ra** [rahulsainlll/git-trace#121]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

As per issue #50, @tarunkumar2005 is not currently handling the integration of Google/GitHub authentication, which is essential for enhancing user login experience and security. Additionally, my issue #106 requires GitHub authentication to work properly, so I am raising this issue to ensure it gets addressed.

### Describe your solution to problem

Implement authentication using Google and GitHub to allow users to log in with their existing accounts. This will provide a more seamless and secure login option. Utilize platforms like OAuth to manage the authentication process efficiently.

### Describe alternatives you have considered

As an alternative, we could integrate other identity providers like Twitter or Facebook for login, but Google and GitHub are currently more commonly used in our user base.

### Additional context

Please prioritize this feature, as it is critical for issue #106. 

**Labels:**
- GSSoC-ext
- Hacktoberfest

**Comment by codebysid** [comment]
assign me

**Comment by codebysid** [comment]
assign me @amitb0ra

**Comment by tarunkumar2005** [comment]
@codebysid Please wait if the issue is valid then either mentor or PA of this project will assign you amitb0ra is a contributor too so he can't assign and as long as i know PA specifically mentioned me that we are not timplementing the oauth right now from what i understood i can't say about that but they will assign you if the issue is valid and first chance is for @amitb0ra if he/she doesn't complete it then you will be assigned so you need to wait until then.

**Comment by tarunkumar2005** [comment]
![image](https://github.com/user-attachments/assets/6537e458-b813-411b-922d-7f8c15d51c98)

From this what i understood i am telling that. he said we are not integrating any kind of .....

**Comment by amitb0ra** [comment]
> ![image](https://private-user-images.githubusercontent.com/158801564/378177702-6537e458-b813-411b-922d-7f8c15d51c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjEwMDMsIm5iZiI6MTcyOTQyMDcwMywicGF0aCI6Ii8xNTg4MDE1NjQvMzc4MTc3NzAyLTY1MzdlNDU4LWI4MTMtNDExYi05MjJkLTdmOGMxNWQ1MWM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMDM4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmJiNDBiM2QxOGIyNjhhMTIwYjU2ZWJkOWQwOGFlNGYxZGQ2NzhlZDE2NzFjN2U5NTUxZWVjMzg0MWJjYmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kfswBBuRNi6FzQ5u5nziVE2OrJXMevqBpwveLF6xYFk)
> 
> From this what i understood i am telling that. he said we are not integrating any kind of .....

yeah but for users page to work properly i need github auth right?

**Comment by rahulsainlll** [comment]
we don't need any kind  of good auth rn

**Comment by amitb0ra** [comment]
> we don't need any kind of good auth rn

so, how should i proceed with Users Activity Page #106
just github auth on that page like to link your account?
