### ISSUE TITLE
📑 Feature Request: Integrate Password Recovery Feature

### ISSUE THREAD

**Issue by saras-69** [rahulsainlll/git-trace#127]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Users may get locked out of their accounts due to forgotten passwords, which can hinder their experience and limit platform accessibility.

### Describe your solution to problem

Implement a password recovery feature that allows users to reset their password via an OTP or recovery link sent to their registered email. After verifying their identity, users can set a new password to regain access seamlessly.

### Describe alternatives you have considered

Allowing users to reset passwords through customer support, but this approach may delay access and impact user experience.
Using security questions as a recovery option, though it might compromise security if not implemented carefully.

### Additional context

This feature would enhance the platform’s usability and minimize user frustration due to forgotten credentials, contributing to better user retention.

### Add Relevant Screenshot (if available)

![Screenshot 2024-10-20 025545](https://github.com/user-attachments/assets/3769c077-21dc-4cc7-953c-96bd4f398e82)
![Screenshot 2024-10-15 022439](https://github.com/user-attachments/assets/48924af4-be88-4b02-9de0-732a9ea2c7b5)
![Screenshot 2024-10-15 024732](https://github.com/user-attachments/assets/26b59dd0-984f-485c-a5fb-cef1d8fe7325)

https://github.com/user-attachments/assets/05870bae-75de-4aaf-9e66-419a5ee98180

https://github.com/user-attachments/assets/f38e2d71-21e9-432f-b8d9-eb910f5b340d

**Comment by rahulsainlll** [comment]
no needed

**Comment by saras-69** [comment]
@rahulsainlll as you have login feature then this feature would enhance the platform’s usability and minimize user frustration due to forgotten credentials, contributing to better user retention.

**Comment by saras-69** [comment]
He

> @rahulsainlll as you have login feature then this feature would enhance the platform’s usability and minimize user frustration due to forgotten credentials, contributing to better user retention.

Hey @rahulsainlll please look into this.
