### ISSUE TITLE
Incorrect toast description after registration

### ISSUE THREAD

**Issue by Visweswar39** [rahulsainlll/git-trace#13]
Even after successfully registering, The toast description shows "Failed to create an account, please try again" while the toast title says "Registration Successful". This leads to confusion among the users about whether the account creation is successful. Please change the toast description to "Successfully created an account, please log in".

**Steps to reproduce the issue**
1.  Go to the signup page.
2.  Create a new account.
3. Watch the little toast in the bottom right!

![git trace register issue](https://github.com/user-attachments/assets/3413f8c6-8119-47e6-9510-897aa66fa36c)

**Comment by rahulsainlll** [comment]
We will fix the issue ASAP!

**Comment by Visweswar39** [comment]
@rahulsainlll  I just created a pr, please verify ;)

**Comment by rahulsainlll** [comment]
> @rahulsainlll I just created a pr, please verify ;)

Done sir!

Thanks for your contribution!
