### ISSUE TITLE
📑 Feature Request: Enhance Landing Page

### ISSUE THREAD

**Issue by dev129** [rahulsainlll/git-trace#135]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

The landing page of your website can be improved to a lot of extent. 

### Describe your solution to problem

The landing page is not looking good and to get more people the user intefrace must look interesting.

**Comment by Aarzookhunger** [comment]
UI changes are not needed as of now, if any functionality you want to add you can open a new issue for that.!
