### ISSUE TITLE
📑 Feature Request: Add a bar/line chart showing daily/monthly/yearly issue counts

### ISSUE THREAD

**Issue by mehul-m-prajapati** [rahulsainlll/git-trace#140]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

**Issue Creation Over Time**: A line or bar chart showing the number of issues created over a specific time period (daily, weekly, monthly) to identify trends.

**Open vs. Closed Issues:** A pie chart or stacked bar chart illustrating the ratio of open to closed issues, providing a quick overview of the project’s current status.

**Comment by mohdshubair313** [comment]
Hey @mehul-m-prajapati I can work on this please assign this to me

**Comment by mehul-m-prajapati** [comment]
@mohdshubair313 : surely, please give me owner permission for this repo

**Comment by mohdshubair313** [comment]
what that means? @mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
@mohdshubair313 - That means you need to read gssoc guidelines.

I have spend time to open issue so, I will get assigned. 

You need to create your own issues

**Comment by mohdshubair313** [comment]
ok sir no problem
