### ISSUE TITLE
📑 Feature Request: Adding Styling to the Login and Register Button

### ISSUE THREAD

**Issue by abishek1740P** [rahulsainlll/git-trace#142]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Enhancing the styling of Login and Register buttons improves user engagement by making call-to-actions clearer, more accessible, and visually appealing.

### Describe your solution to problem

Implementing visually distinct styles and interactive effects for Login and Register buttons enhances user engagement and clarity in the authentication process.

### Add Relevant Screenshot (if available)

![image](https://github.com/user-attachments/assets/4e317763-7153-4d4f-8e48-51d48a881a20)
![image](https://github.com/user-attachments/assets/27cbe9e8-4043-44c7-bb42-24d233b5f30a)

**Comment by abishek1740P** [comment]
@rahulsainlll Also please , Consider this under gssoc-ext

**Comment by abishek1740P** [comment]
@Aarzookhunger Yes . I'd like to style the button.

**Comment by Aarzookhunger** [comment]
@abishek1740P sorry but that's not reqd. If you want to add some functionality that'll actually improve website in terms of working you can go ahead and create issue for the same.!
