### ISSUE TITLE
📑 Feature Request: Add our contributor page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [rahulsainlll/git-trace#146]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

I can design a beautiful contributor page that will show the hard work of our developer to build this website
And many more feature I can design for both dark and light mode

**Comment by Aarzookhunger** [comment]
Issue already opened.
