### ISSUE TITLE
📑 Feature Request: Add Google translator for multi language support 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [rahulsainlll/git-trace#147]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

This will provide user to get access of different languages
It has option in international languages as well as Indian language

**Comment by Aarzookhunger** [comment]
Issue already exists
