### ISSUE TITLE
📑 Feature Request: Redesign the Register/signup page 

### ISSUE THREAD

**Issue by REHAN-18** [rahulsainlll/git-trace#149]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

I want to redesign the signup/Register page the currently is looking dull & doest suit the this site ..

@rahulsainlll pls assign me !!

**Comment by Aarzookhunger** [comment]
@REHAN-18 re-design in what sense? It matches pretty well with the retro design of the website.

**Comment by REHAN-18** [comment]
@Aarzookhunger the ui of the signup

**Comment by Aarzookhunger** [comment]
@REHAN-18 I think it's fine and does what it is supposed to. Kindly open another issue if you want to contribute in terms of enhancing functionality, UI is fine.
