### ISSUE TITLE
Implement Issue open/close message workflow automation🚀

### ISSUE THREAD

**Issue by amiya-cyber** [rahulsainlll/git-trace#152]
Workflow Description:

This workflow automates messages when an issue is opened or closed. When a new issue is opened, it posts a welcome message to guide the submitter. When an issue is closed, it posts a thank-you message, acknowledging the resolution.

This helps improve communication and maintain consistency in issue management.

please assign me with level3 label @rahulsainlll

**Comment by Aarzookhunger** [comment]
@amiya-cyber posts as in where? e-mail or comment section or somewhere else'?

**Comment by amiya-cyber** [comment]
And also I have more workflow for your project hoping to work more in your project thank you @rahulsainlll

**Comment by Aarzookhunger** [comment]
> Directly to email as well as comments whenever some one open or close a issue assign me with level 3 label thank you @rahulsainlll

I'll assign you the label (2/3) once you open a pr for the same, so that I can have a look on complexity of implementation and label accordingly!

**Comment by amiya-cyber** [comment]
> > Directly to email as well as comments whenever some one open or close a issue assign me with level 3 label thank you @rahulsainlll
> 
> I'll assign you the label (2/3) once you open a pr for the same, so that I can have a look on complexity of implementation and label accordingly!

Ok sure
