### ISSUE TITLE
📑 Feature Request: Add Multi-Language Support Using Language Translator

### ISSUE THREAD

**Issue by TBorundia** [rahulsainlll/git-trace#154]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Implement a language translation API to allow dynamic switching between multiple languages.
Add a language selector (dropdown or buttons) to the UI for easy language switching.

**Comment by Aarzookhunger** [comment]
issue already there regarding the same, so closing this one.
