### ISSUE TITLE
UI enhancements, Bug fixtures: both Search buttons get's updated when clicked on one.

### ISSUE THREAD

**Issue by Atishyy27** [rahulsainlll/git-trace#16]
![image](https://github.com/user-attachments/assets/aa701871-636c-4dfb-8ee1-61082463f91e)

**Comment by Atishyy27** [comment]
Will design the UI on figma

**Comment by Utkarshrajmishra** [comment]
Hi, is this issue open for work? If so, could you please assign it to me? I would love to contribute.

**Comment by rahulsainlll** [comment]
> Will design the UI on figma

Send here when you are done!

**Comment by rahulsainlll** [comment]
> Hi, is this issue open for work? If so, could you please assign it to me? I would love to contribute.

Its open!
