### ISSUE TITLE
📑 Feature Request: chabge ui of the navbar

### ISSUE THREAD

**Issue by priyashuu** [rahulsainlll/git-trace#169]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

https://github.com/user-attachments/assets/8df58f41-7f1a-4737-9314-00231ed55bba

**Comment by Aarzookhunger** [comment]
@priyashuu I think navbar is fine the way it is, perhaps PA wants it in that style only.
So closing this one, you can go ahead and open another issue.!
