### ISSUE TITLE
⚙ general issue: Add Copyright Line to Footer

### ISSUE THREAD

**Issue by AnushkaChouhan25** [rahulsainlll/git-trace#171]
### Please describe your feature request related to a problem?

Add a copyright line in the footer section of the website to indicate the ownership and protection of content.

### Describe your solution to problem

- The footer should display a copyright line, such as:
  © 2024 git-trace. All rights reserved.
- The year should update dynamically based on the current year.
- The text should be styled consistently with the rest of the footer content for a cohesive look.

**Comment by rovertrack** [comment]
Quick question do we have to like do some documents or go to legal offices or apply online for the copyright thing or we can just add it to our website ?

**Comment by AnushkaChouhan25** [comment]
Only add to our website - 
© 2024 git-trace. All rights reserved
  Made with ♥ in India

**Comment by rovertrack** [comment]
Can I take on this issue 
If I can assign me.
