### ISSUE TITLE
📑 Feature Request: Design Eye-Catching Progress Bar and a Back to top button for UI Aesthetics 

### ISSUE THREAD

**Issue by Edasgh** [rahulsainlll/git-trace#172]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Describe your solution to problem

:red_circle: Add a progress bar and a back to top button in all the pages
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** :
- Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process, and a back to top button helps users to go back to the top-part improving usability and navigation.

- Improved Aesthetics: Customizing the  progress bar and the back to top button to match the UI enhances the overall look and feel of the application, making it more attractive to users.

- Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.

Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

**Comment by Edasgh** [comment]
> @Edasgh keep it b&w to match with website design.!

Does it look good?
https://www.loom.com/share/683f0c3ec9f046d9a52545ac92382a01?sid=cff6df0c-45bb-4035-bfc1-946a70f92435

**Comment by Aarzookhunger** [comment]
> > @Edasgh keep it b&w to match with website design.!
> 
> Does it look good? https://www.loom.com/share/683f0c3ec9f046d9a52545ac92382a01?sid=cff6df0c-45bb-4035-bfc1-946a70f92435

yup gr8!
