### ISSUE TITLE
Addition of forget password functionality (Backend and frontend)

### ISSUE THREAD

**Issue by Sourabh782** [rahulsainlll/git-trace#21]
I wanted to add a forget password functionality

Screenshot:
![Screenshot 2024-10-02 111905](https://github.com/user-attachments/assets/235ad0f5-c301-46e6-8c1b-4decae7c4da9)

Currently its missing forget password functionality, making it hard to login once we forget password

**I want to work on this issue.**

under: GSSOC-ext and hacktober

**Comment by rahulsainlll** [comment]
Yeah you can do it now!

**Comment by Sourabh782** [comment]
Thanks @rahulsainlll, working on it

**Comment by Sourabh782** [comment]
hii @rahulsainlll, which type of password reset you want? 
1. just by provideing correct email address
2. otp based? (requires changed in db)

**Comment by rahulsainlll** [comment]
otp based

**Comment by Sourabh782** [comment]
> otp based

Okkk working on it
