### ISSUE TITLE
made header responsive 

### ISSUE THREAD

**Issue by rahulsainlll** [rahulsainlll/git-trace#3]
you will find header in components/page-header.tsx

**Comment by Masood-ul-Rehman** [comment]
I want to work on it, can you please assign this to me?

**Comment by Masood-ul-Rehman** [comment]
https://github.com/rahulsainlll/git-trace/pull/5 @rahulsainlll Please review

**Comment by rahulsainlll** [comment]
> https://github.com/rahulsainlll/git-trace/pull/5 @rahulsainlll Please review

Sure sir
