### ISSUE TITLE
Create a Custom 404 Page for Better User Experience

### ISSUE THREAD

**Issue by myselfshivams** [rahulsainlll/git-trace#31]
Currently, when users encounter a broken or non-existent link, the website shows the default 404 error page. To enhance the user experience, we should create a custom 404 page with a user-friendly design and helpful navigation options (e.g., a link back to the homepage or other important sections). This will help guide users when they land on a missing page, improving overall usability.

Labels:
- gssoc
- hacktoberfest

@rahulsainlll  Please assign this task to me (@myselfshivams).

**Comment by rahulsainlll** [comment]
instead of this you can make a classic toaster ref codeforces

**Comment by myselfshivams** [comment]
> instead of this you can make a classic toaster ref codeforces

ohk I will create pls assign this to me
