### ISSUE TITLE
Add Missing Meta Tags, Robots.txt, and Sitemap for Improved SEO

### ISSUE THREAD

**Issue by myselfshivams** [rahulsainlll/git-trace#32]
The website currently lacks essential SEO elements such as meta tags, robots.txt, and a sitemap. These are critical for optimizing the site’s visibility on search engines and improving overall discoverability.

Proposed Solution:
- Meta Tags: Add relevant meta tags (title, description, keywords, Open Graph, Twitter cards, etc.) to improve SEO and social sharing.
- Robots.txt: Create a robots.txt file to guide web crawlers and define which pages should be indexed.
- Sitemap: Generate an XML sitemap to ensure proper indexing by search engines.

Benefits:
 - Improved visibility on search engines.
- Better control over what pages should or should not be crawled.
- Enhanced user engagement via optimized metadata for sharing on social platforms.

Labels:
- gssoc
- hacktoberfest
@rahulsainlll  Please assign this task to me(@myselfshivams).

**Comment by rahulsainlll** [comment]
do it!

**Comment by myselfshivams** [comment]
@rahulsainlll Please add labels as gssoc will not accept.
