### ISSUE TITLE
 Dark Mode Toggle for Improved User Experience

### ISSUE THREAD

**Issue by yakhilgithub** [rahulsainlll/git-trace#41]
Description:
I think it would be great to add a dark mode toggle to our website, allowing users to switch between light and dark themes. Dark mode has become really popular, and giving users this option will make our site more user-friendly.

Why This is Important:
-User Comfort: Dark mode is easier on the eyes, especially in low-light settings.
-Customization: Users can choose their preferred theme based on what they find comfortable.
-Modern Look: It’ll give our site a more modern and professional feel.
-Accessibility: It helps users with visual sensitivities or those who prefer dark mode.

Proposed Solution:
-Add a toggle switch (maybe in the header or settings) to let users switch between light and dark themes.
-Store the user’s choice, so the site remembers their preference when they come back.
-Make sure everything on the site adjusts smoothly to the dark theme, with no issues in readability or functionality.

Design Ideas:
-A simple toggle that switches the theme.
-Could even use fun icons like a sun and moon for the toggle!

Impact:
This will make our site more flexible and appealing to users who like having control over their browsing experience.

I would like to work on this issue and take the responsibility of implementing these changes. Please assign me this issue, and kindly add the respective labels, including the level 3 label.

**Comment by rahulsainlll** [comment]
level 3 for a toggle?

**Comment by Aarzookhunger** [comment]
@yakhilgithub Make sure you change other elements accordingly as well so that they color co-ordinate well.

**Comment by rajgharat07** [comment]
I would also like to contribute to this.

**Comment by Aarzookhunger** [comment]
@yakhilgithub Are you working on this issue? Some other contributors are also willing to take this issue so it would be great if you confirm your presence.

**Comment by toufiqfarhan0** [comment]
@yakhilgithub are you still workin on it? if not i would like to work on it

**Comment by toufiqfarhan0** [comment]
@rahulsainlll i would like to work on this

**Comment by rahulsainlll** [comment]
work on it. DO provide a video of it also after making it

**Comment by toufiqfarhan0** [comment]
> work on it. DO provide a video of it also after making it

Sure ser!
