### ISSUE TITLE
Image optimization in the blog card component

### ISSUE THREAD

**Issue by adityapandey23** [rahulsainlll/git-trace#48]
![image](https://github.com/user-attachments/assets/6c8c22f7-c26b-47a4-a728-97582e71a308)

In the blog card component we can use Image component from nextjs, which will optimize the image when the site is in production.
It's a minor change, if you feel it's worth it then you can assign me this issue. Otherwise you can close this issue.

**Comment by rahulsainlll** [comment]
yeah do it

**Comment by adityapandey23** [comment]
Hey @rahulsainlll 
I have created a pr #57
