### ISSUE TITLE
Enhancing the login, signup design for better UI/UX and get user a better view on the website

### ISSUE THREAD

**Issue by tarunkumar2005** [rahulsainlll/git-trace#50]
Enhancing the login, signup design for better UI/UX and get user a better view on the website

So i want to enahace the ui ux of the login and signup page just like a professional website so assign this to me under gssoc 2024 ext and hacktoberfect @rahulsainlll

**Comment by rahulsainlll** [comment]
any particular design ? u got

**Comment by tarunkumar2005** [comment]
![image](https://github.com/user-attachments/assets/5c13a625-a430-4404-aca1-ad54c1105985)

Something like this. If you want or i can create better and awersome just a demo

**Comment by tarunkumar2005** [comment]
@rahulsainlll

**Comment by harish08102004** [comment]
Hey @rahulsainlll may be I can work on this.

**Comment by tarunkumar2005** [comment]
@rahulsainlll Can you respond if you didn't liked the design or anything else you didn't assigned or responded to my issue.

**Comment by rahulsainlll** [comment]
yeah design is good but we are not integrating any kind of so you can just improve the current desin

**Comment by amitb0ra** [comment]
can i add google/github auth? as  @tarunkumar2005 isn't doing it.

**Comment by rahulsainlll** [comment]
> can i add google/github auth? as @tarunkumar2005 isn't doing it.

don't need google auth
