### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by Meetjain1** [rahulsainlll/git-trace#56]
Dear Project Admin @rahulsainlll 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by Meetjain1** [comment]
@rahulsainlll why r u ignoring ?

**Comment by rahulsainlll** [comment]
> @rahulsainlll why r u ignoring ?

No no there were like 8-9 issue and PRs so it missed.

I have corrected all the labels ser. See for yourself anyways i will check again. Thank you

**Comment by Meetjain1** [comment]
> > @rahulsainlll why r u ignoring ?
> 
> No no there were like 8-9 issue and PRs so it missed.
> 
> I have corrected all the labels ser. See for yourself anyways i will check again. Thank you

Its okay , But still labels are not correct please read my above comment again of correct labels @rahulsainlll

**Comment by rahulsainlll** [comment]
now check ser in the merged PRs and Currenct PRs also updating the issues now. If you see any mistake their do let me know!

**Comment by Meetjain1** [comment]
@rahulsainlll Yes perfect !
