### ISSUE TITLE
Add Pagination to Blog Page

### ISSUE THREAD

**Issue by SurajSakhare100** [rahulsainlll/git-trace#59]
![blog](https://github.com/user-attachments/assets/f8bebd35-233c-49dd-92e2-e4e9a4363318)

**Description:**  The blog page currently displays all blog posts at once, which can lead to performance issues and a poor user experience, especially as the number of blog posts grows. Pagination should be implemented to improve loading times and enhance usability by limiting the number of blog posts displayed per page.

@rahulsainlll , If there are more tasks related to this or additional issues, feel free to assign them to me, and I will resolve them. Please assign this issue to me under GSSoC and Hacktoberfest.

**Comment by rahulsainlll** [comment]
yeah but this if we got more than 6 blogs then see this pagination
