### ISSUE TITLE
Search by URL option

### ISSUE THREAD

**Issue by SatyanshMittal** [rahulsainlll/git-trace#6]
Add a option so that user can search repo by providing it's url.

**Comment by rahulsainlll** [comment]
ok i'll do this in v2

**Comment by syedubaid11** [comment]
can you assign me ?

**Comment by rahulsainlll** [comment]
> can you assign me ?

sure but explain first how you gonna do this ? and what about the ui

**Comment by syedubaid11** [comment]
allowing users to input the profile url in the owner tab and then replacing the initial part of the url for the get request 

something like this -->       const username = url.replace('https://github.com/', '');

**Comment by syedubaid11** [comment]
> ok then make ui little similar

sure
