### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by PankajKumardev** [rahulsainlll/git-trace#62]
I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

[x ] I am contributing under GSSoC-ext
[x ] I am contributing under hacktoberfest
[x ] I follow contribution guidelines

**Comment by Aarzookhunger** [comment]
#30 already raised issue.

**Comment by PankajKumardev** [comment]
@Aarzookhunger so assign this to me , i can do this
