### ISSUE TITLE
Documentation: Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [rahulsainlll/git-trace#66]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC Ext & level1 Labels.

**Comment by Aarzookhunger** [comment]
You can proceed.

**Comment by KiranBaliga** [comment]
@Aarzookhunger Please review the PR and action accordingly. 

Please add level1 and gssoc-ext labels to the linked PR. Thank you!
