### ISSUE TITLE
add footer

### ISSUE THREAD

**Issue by rahulsainlll** [rahulsainlll/git-trace#7]
simple footer with necessary info

**Comment by syedubaid11** [comment]
can you assign me?

**Comment by rahulsainlll** [comment]
ok but has to be classic its should be meet with website 

if you want i can tell you little bit how to contribute to probject?

**Comment by syedubaid11** [comment]
sure

**Comment by rahulsainlll** [comment]
read this for ref: https://github.com/firstcontributions/first-contributions#first-contributions

just don't forget to make a branch 
for this one its not that much but if wanna lets how to open-s then do it
