### ISSUE TITLE
🐛 Bug Report: Fix button style 

### ISSUE THREAD

**Issue by rahulsainlll** [rahulsainlll/git-trace#72]
### Describe the bug.

Buttons is not matching with theme logout you just have to revert it 

### Screenshot.

<img width="240" alt="Screenshot 2024-10-09 at 10 41 18 PM" src="https://github.com/user-attachments/assets/c7b7ff4d-f79b-47eb-b4a2-da79d652e072">

make it just as before 

<img width="177" alt="Screenshot 2024-10-09 at 10 42 23 PM" src="https://github.com/user-attachments/assets/37c9dde6-5eb6-41d4-9196-39903cc8174b">

or can make it better which match it with theme;

**Comment by Virtual4087** [comment]
I would like to work on this

**Comment by Virtual4087** [comment]
![image](https://github.com/user-attachments/assets/ce68b0db-20b7-40aa-9cd9-25e7f10bec52)
![image](https://github.com/user-attachments/assets/9edac377-6200-4a1f-80cd-b69097f4eb55)

I've started working on this and here are two proposals. Do you like any of them?

**Comment by Virtual4087** [comment]
https://github.com/user-attachments/assets/cf2aa804-efcb-47b6-b920-8cecb3757ee5

or maybe this?

**Comment by Virtual4087** [comment]
Please let me know @rahulsainlll

**Comment by toufiqfarhan0** [comment]
@rahulsainlll 

https://github.com/user-attachments/assets/5a546dd0-594c-453f-8724-ccca58ee9c7c

**Comment by Aarzookhunger** [comment]
@Virtual4087 @toufiqfarhan0 the issue was not assigned to anyone of you, yet you guys created a pull request for it.
Wait for project admin to approve before you start working on the issue.

**Comment by Virtual4087** [comment]
@Aarzookhunger Got it. Sorry for creating a pr. Should I close it?

**Comment by toufiqfarhan0** [comment]
@Aarzookhunger I Apologie! today was my first day
