### ISSUE TITLE
📑 Feature Request: integrating dark mode

### ISSUE THREAD

**Issue by Sourabh782** [rahulsainlll/git-trace#73]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

Adding feature of dark mode, so make app better for night working and less eye strain

**Comment by toufiqfarhan0** [comment]
I would like to work on it! Assign me

**Comment by Sourabh782** [comment]
@toufiqfarhan0 I have requested it before you

**Comment by toufiqfarhan0** [comment]
> @toufiqfarhan0 I have requested it before you

Ok !

**Comment by Sourabh782** [comment]
Hello @Aarzookhunger, I see you mentioning this issue at no.41, if theres no reply then can I work on it?

**Comment by toufiqfarhan0** [comment]
resolves #102
