### ISSUE TITLE
📑 Feature Request:  Add a "Frequently Asked Questions (FAQ)" Section to the Website

### ISSUE THREAD

**Issue by Zaki2409** [rahulsainlll/git-trace#83]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

The website currently lacks a dedicated "Frequently Asked Questions (FAQ)" section, making it harder for users to find quick answers to common queries.

### Describe your solution to problem

Add a "Frequently Asked Questions (FAQ)" page to the website. This section will address common questions users may have about the platform, features, usage.

### Describe alternatives you have considered

Embedding FAQ content within existing help or support pages.

### Additional context

This feature will improve user experience by providing quick access to answers, reducing the need for direct support.

### Add Relevant Screenshot (if available)

example : ( picture )

![git travr](https://github.com/user-attachments/assets/6c8f69e9-7b15-4d22-a61d-fbb023e4968b)

Hello, @rahulsainlll  

/assign

**Comment by rahulsainlll** [comment]
done! just make sure it match theme

**Comment by Zaki2409** [comment]
on it!!

**Comment by Zaki2409** [comment]
Hi @rahulsainlll,

Could you please review my pull request for the FAQ section? Your feedback would be appreciated!

Thanks!
