### ISSUE TITLE
add a to-do in each issue to track the progress

### ISSUE THREAD

**Issue by rahulsainlll** [rahulsainlll/git-trace#9]
like on each issue user can add a to-do's in a repo and by clicking the tick we calculate the process on each issue

**Comment by rahulsainlll** [comment]
ok so you have to make a todo schema for every repository / issue after saving the repos/issue in dashboard user can add his own todos in it we have to keep track of them 

Features:- 
- add todo
- edit todo 
- dlt todo
- can mark as done on every todo ( just check boxes )
- when repo/issue dlt so as todo with it 

basically curd operation on every todo 

make it properly so it won't affect current user 
ui should be decent 

if you can do all of these I can assign you this issue

**Comment by malisettisamrat** [comment]
@rahulsainlll, so basically I have to show todo list fields for CRUD operations below the dashboard bookmarks to add his todos. right?

**Comment by rahulsainlll** [comment]
they can add todos just below the repo/issue

ex .
repo/issue
-todo
-todo

next repo

kinda like a dropdown just a todo button when they press they see just blow a a writing space where they can write them 

just make one will update the things later

**Comment by malisettisamrat** [comment]
@rahulsainlll got an idea how should I display them below repo/issues . I will work on it! Thank you!

**Comment by rahulsainlll** [comment]
dropdown triggers with todo button

**Comment by malisettisamrat** [comment]
@rahulsainlll todo fields should be present in the dropdown? Right?

**Comment by rahulsainlll** [comment]
right just make one button todo that open dropdown and there user can dlt update etc

**Comment by malisettisamrat** [comment]
@rahulsainlll, I don't see the .env.example file for setting up the .env file. Could you please help me out!

**Comment by ShivanshPlays** [comment]
Hi @rahulsainlll I have read the conversation above and I've understood the requirements, I would be glad to add this todo feature if you could assign it to me.

**Comment by rahulsainlll** [comment]
> Hi @rahulsainlll I have read the conversation above and I've understood the requirements, I would be glad to add this todo feature if you could assign it to me.

Sure go ahead! feel free to ask again if have any doubts

**Comment by ShivanshPlays** [comment]
![image](https://github.com/user-attachments/assets/f3fc8c8f-d75a-4b23-8670-4f083eaffe7b)
Hi, there is no .env.example can you please provide one so that I can start working

**Comment by ShivanshPlays** [comment]
I think we can close this Issue now
