### ISSUE TITLE
📑 Feature Request:  Email Verification via OTP

### ISSUE THREAD

**Issue by abir499-ban** [rahulsainlll/git-trace#96]
### IMPORTANT TO CHECK BEFORE ISSUE

- [x] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

I genuinely loved the product and the application, given that using git and github has become sort of a daily activity. 
Currently, users are registered based on their email addresses, but there's no verification in place to ensure the validity of the email provided. Implementing a validation process, such as sending an OTP to verify the user's email, would significantly improve both the security and the practicality of the application. This additional layer of verification will ensure that only legitimate users with valid email addresses are registered, boosting user trust and safeguarding the platform from misuse.

### Describe your solution to problem

I would like to use the [Nodemailer](https://www.npmjs.com/package/nodemailer) npm package to set up a smtp server to send otp to the email, entered on the Resgister page input by the user, and store the otp in the database. Then would ask the user to enter the opt sent to him/her by the email. If the opt entered by him/her matches the lastest opt stored in the database with his/her email, we would allow him to register else not.

### Additional context

For storing the OTP I would like to create a new OTP Schema in the database, which will have 3 feilds 

- Email : storing the email, where the OPT is to be sent.
- Value : the random six digit value of the OTP
- isConsumed : a boolean value which would indicate whether the otp is used up or not. If it is created and not used up for verifying, then it would be false and if used up then true.

@rahulsainlll  please assign me this issue

**Comment by rahulsainlll** [comment]
We don't need this right now
