### ISSUE TITLE
📑 Feature Request: Addition of a Dockerfile

### ISSUE THREAD

**Issue by unknown91tech** [rahulsainlll/git-trace#98]
### IMPORTANT TO CHECK BEFORE ISSUE

- [X] You check that same issue is not present in the repository
- [X] You have read contribution guidelines and rules

### Please describe your feature request related to a problem?

We don't have to install anything extra on our local machine instead all the things will be installed into a container and we can install and run everything in one command.

### Describe your solution to problem

@rahulsainlll Addition of the docker file will help in smoother running of the project locally.

**Comment by Aarzookhunger** [comment]
This issue has already been assigned to someone so closing this!
